import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthWrapper from "./auth_wrapper";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { AppMedicationContext, AppWrapper } from "./context";
import { getMedications } from "./lib/actions";
import Script from "next/script";
import { useContext } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gestão Med",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const { status, data } = await getMedications()
  return (
    <html lang="pt-br">
      <body className={inter.className}>
      <script src="https://app.aminos.ai/js/chat_plugin.js" data-bot-id="25264"></script>

        <AuthWrapper>
          <AppWrapper >
            {children}
          </AppWrapper>
        </AuthWrapper>
        <ToastContainer />
      </body>
    </html>
  );
}
