import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthWrapper from "./auth_wrapper";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { AppWrapper } from "./context";
import { getMedications } from "./lib/actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gestão Med",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const { status, data } = await getMedications()
  return (
    <html lang="pt-br">
      <body className={inter.className}>

        <AuthWrapper>
          <AppWrapper apiData={data}>
            {children}
          </AppWrapper>
        </AuthWrapper>
        <ToastContainer />
      </body>
    </html>
  );
}
